### ISSUE TITLE
pass all outputs to Slack

### ISSUE THREAD

**Issue by samanemami** [pathwaycom/llm-app#72]
### Steps to reproduce

Is there any way to pass all outputs to Slack for alert?

### Relevant log output

```text
Sorry, it is not a bug, but rather an ask for a favor
```

### What did you expect to happen?

No matter if it is alert or not, pass it to slack

### Version

Current main branch

### OS

Linux

### On which CPU architecture did you run Pathway?

x86-64

**Comment by dxtrous** [comment]
Hi @samanemami yes, it is possible to push changes to any Pathway table to Slack. In particular, you can write query replies into a Pathway table, then push changes to this table to a Slack output connector.
Here is another example of code using a custom-made Slack connector that pushes changes to a table called `t_alert` to Slack: https://pathway.com/developers/tutorials/realtime-log-monitoring.
