### ISSUE TITLE
Question: local HF model + Auto update index from specific folder

### ISSUE THREAD

**Issue by Maxamed** [pathwaycom/llm-app#74]
### Steps to reproduce

Which option to use if the usecase is :
1. Using local HF model
2. Auto update index from specific folder
3. Store embeddings in database 

Love this project !

### Relevant log output

```text
Not available
```

### What did you expect to happen?

Easier way to deploy and use 

### Version

1

### OS

MacOS

### On which CPU architecture did you run Pathway?

ARM64 (AArch64, Apple silicon)

**Comment by dxtrous** [comment]
You can use the "contextful" example as a template (or "alerting", or "unstructured" depending on your need).

Then, replace any references in the code to OpenAI with those to HuggingFace - as in the "local" example.
