### ISSUE TITLE
Shei

### ISSUE THREAD

**Issue by ArjitTiwarii** [pathwaycom/llm-app#85]
### Steps to reproduce

Big reprt

### Relevant log output

```text
Bug reprt
```

### What did you expect to happen?

Shetkls

### Version

Wjefvn

### Docker Versions (if used)

Whn

### OS

Linux

### On which CPU architecture did you run Pathway?

None

**Comment by KamilPiechowiak** [comment]
Hey @ArjitTiwarii,
I am closing this issue as it doesn't contain any information about the bug. If you really need help feel free to open a new issue.
